[package]
name = "cloud-detect"
version = "0.5.0"
edition = "2021"
authors = ["Nikhil Prabhu <nikhilprabhu98@gmail.com>"]
description = "Detect a host's cloud service provider"
repository = "https://github.com/nikhil-prabhu/cloud-detect"
license = "GPL-3.0"
documentation = "https://docs.rs/cloud-detect"
keywords = ["cloud", "aws", "azure", "gcp", "hyperscaler"]

[dependencies]
reqwest = { version = "0.11.18", features = ["json"] }
tokio = { version = "1.29.1", features = ["full"] }
serde = { version = "1.0.188", features = ["derive"] }
async-trait = "0.1.73"
tracing = "0.1.40"
