[package]
name = "cloud-detect"
version = "0.4.0"
edition = "2021"
authors = ["Nikhil Prabhu <nikhilprabhu98@gmail.com>"]
description = "Detect a host's cloud service provider"
repository = "https://github.com/nikhil-prabhu/cloud-detect"
license = "GPL-3.0"
documentation = "https://docs.rs/cloud-detect"
keywords = ["cloud", "aws", "azure", "gcp", "hyperscaler"]

[dependencies]
lazy_static = "1.4.0"
reqwest = { version = "0.11.18", features = ["blocking"] }
tokio = { version = "1.29.1", features = ["full"] }

[features]
blocking = []
